<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Designnbuy\OrderTicket\Block\Adminhtml\OrderTicket\Edit\Tab\General\Details
 */

$customerLink = $block->getCustomerLink();
?>
<div class="admin__page-section-item orderticket-request-details">
    <div class="admin__page-section-item-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Request Details') ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <table class="admin__table-secondary">
            <tr>
                <th><?php /* @escapeNotVerified */ echo __('ID') ?></th>
                <td><?php /* @escapeNotVerified */ echo __('#') . $block->getOrderTicketData('increment_id') ?></td>
            </tr>
            <tr>
                <th><?php /* @escapeNotVerified */ echo __('Order ID') ?></th>
                <td><a href="<?php /* @escapeNotVerified */ echo $block->getOrderLink() ?>"><?php /* @escapeNotVerified */ echo __('#') . $block->getOrderIncrementId() ?></a></td>
            </tr>
            <tr>
                <th><?php /* @escapeNotVerified */ echo __('Customer Name') ?></th>
                <td>
                    <?php
                    if ($customerLink) {
                        echo '<a href="' . $customerLink . '">';
                    }
                    /* @escapeNotVerified */ echo $block->getCustomerName();
                    if ($customerLink) {
                        echo '</a>';
                    }
                    ?>
                </td>
            </tr>
            <tr>
                <th><?php /* @escapeNotVerified */ echo __('Email Address') ?></th>
                <td><a href="mailto:<?php /* @escapeNotVerified */ echo $block->getCustomerEmail() ?>"><?php /* @escapeNotVerified */ echo $block->getCustomerEmail() ?></a></td>
            </tr>
            <tr>
                <th><?php /* @escapeNotVerified */ echo __('Contact Email Address') ?></th>
                <td><?php if ($block->getCustomerContactEmail()): ?><a href="mailto:<?php /* @escapeNotVerified */ echo $block->getCustomerContactEmail() ?>"><?php /* @escapeNotVerified */ echo $block->getCustomerContactEmail() ?></a><?php endif; ?></td>
            </tr>

            <?php if($block->getJobTitle()): ?>
                <tr>
                    <th><?php /* @escapeNotVerified */ echo __('Job Title'); ?></th>
                    <td><?php /* @escapeNotVerified */ echo $block->getJobTitle() ?></td>
                </tr>
            <?php endif; ?>
            
            <?php if($block->getJobId()): ?>
                <tr>
                    <th><?php /* @escapeNotVerified */ echo __('View Job'); ?></th>
                    <td><a target="_blank" href="<?php /* @escapeNotVerified */ echo $block->getJobLink() ?>">
                        <?php /* @escapeNotVerified */ echo __('View Job') ?></a></td>
                </tr>
            <?php endif; ?>
        </table>
    </div>
</div>
