<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Designnbuy\OrderTicket\Block\Adminhtml\OrderTicket\Edit\Tab\General\History" */
?>
<div class="admin__page-section-item order-comments-history orderticket-comments-history" id="orderticket-history-block">
    <div class="admin__page-section-item-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Order Ticket History') ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <div id="history_form" class="orderticket-history-form edit-order-comments">
            <div class="order-history-block">

                <div class="admin__field">
                    <label for="comment_status" class="admin__field-label"><?php /* @escapeNotVerified */ echo __('Status') ?></label>
                    <div class="admin__field-control">
                        <select name="comment[status]" id="comment_status" class="admin__control-select">
                            <?php foreach ($block->getStatuses() as $_code => $_label): ?>
                                <option value="<?php /* @escapeNotVerified */ echo $_code ?>"<?php if ($_code == $block->getOrderTicketData('status')): ?> selected="selected"<?php endif; ?>><?php /* @escapeNotVerified */ echo $_label ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                
                <div class="admin__field">
                    <label class="admin__field-label"
                           for="history_comment"><?php /* @escapeNotVerified */ echo __('Comment Text') ?></label>
                    <div class="admin__field-control">
                        <textarea
                            class="admin__control-textarea"
                            name="comment[comment]"
                            rows="3"
                            cols="5"
                            id="history_comment"></textarea>
                    </div>
                </div>

                <div class="admin__field">
                    <label class="admin__field-label"
                           for="file"><?php /* @escapeNotVerified */ echo __('File') ?></label>
                    <div class="upload-wrapper" data-bind="scope: 'uploader'" data-mage-init='{
                               "Magento_Ui/js/core/app": {
                                   "components": {
                                       "uploader": {
                                            "formElement" : "fileUploader",
                                            "componentType" : "fileUploader",
                                           "component": "Magento_Ui/js/form/element/file-uploader",
                                           "template": "Designnbuy_OrderTicket/components/file-uploader",
                                           "inputName": "ticket",
                                           "name": "ticket",
                                           "fileInputName": "ticket",
                                           "isMultipleFiles": false,
                                           "uploaderConfig": {
                                                "url": "<?php echo $block->getUrl('adminhtml/*/upload'); ?>"
                                           }
                                       }
                                   }
                                }
                            }
                        '>
                        <!-- ko template: getTemplate() --><!-- /ko -->
                    </div>
                </div>

                <div class="admin__field">
                    <div class="order-history-comments-options">
                        <?php if ($block->canSendCommentEmail()): ?>
                            <div class="admin__field admin__field-option">
                                <input name="comment[is_customer_notified]"
                                       class="admin__control-checkbox"
                                       type="checkbox"
                                       id="history_notify"
                                       value="1"/>
                                <label class="admin__field-label"
                                       for="history_notify">
                                    <?php /* @escapeNotVerified */ echo __('Notify Customer by Email') ?></label>
                            </div>
                        <?php endif; ?>
                        <div class="admin__field admin__field-option">
                            <input name="comment[is_visible_on_front]"
                                   class="admin__control-checkbox"
                                   type="checkbox"
                                   id="history_visible"
                                   value="1"/>
                            <label class="admin__field-label"
                                   for="history_visible"> <?php  echo __('Visible on Storefront') ?></label>
                        </div>
                    </div>
                    <div class="order-history-comments-actions">
                        <?php echo $block->getChildHtml('submit_button') ?>
                    </div>
                </div>
            </div>

            <?php if ($block->getComments()): ?>
                <ul class="note-list">
                    <?php foreach ($block->getComments() as $_item): ?>
                        <li>
                            <span class="note-list-date"><?php /* @escapeNotVerified */ echo $block->formatDate($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
                            <span class="note-list-time"><?php /* @escapeNotVerified */ echo $block->formatTime($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
                            <?php if ($_item->getIsAdmin()): ?>
                                <span class="note-list-status"><?php /* @escapeNotVerified */ echo __('Customer Service')?></span>
                            <?php else: ?>
                                <span class="note-list-status"><?php echo $block->escapeHtml($block->getCustomerName())?></span>
                            <?php endif; ?>
                            <span class="note-list-customer">
                                <?php /* @escapeNotVerified */ echo __('Customer') ?>
                                <?php if ($_item->getIsCustomerNotified()): ?>
                                    <span class="note-list-customer-notified"><?php /* @escapeNotVerified */ echo __('Notified') ?></span>
                                <?php else: ?>
                                    <span class="note-list-customer-not-notified"><?php /* @escapeNotVerified */ echo __('Not Notified') ?></span>
                                <?php endif; ?>
                            </span>
                            <?php if ($_item->getComment()): ?>
                                <div class="note-list-comment"><?php echo $block->escapeHtml($_item->getComment(), ['b', 'br', 'strong', 'i', 'u']) ?></div>
                            <?php endif; ?>
                            <?php if ($_item->getFile()): ?>
                                <div class="note-list-comment">
                                    <a target="_blank" href="<?php echo $block->getFile($_item->getFile())?>"><?php echo $_item->getFile() ?></a>
                                </div>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif ?>
        </div>
    </div>
</div>