<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Background background media gallery images template
 *
 * @var $block \Designnbuy\Background\Block\Background\View\Gallery
 */
?>

<?php
    $background = $block->getBackground();
    $galleryImages = $background->getGalleryImages();
?>

<?php if (count($galleryImages)) { ?>
    <div class="background-gallery clearfix">
        <?php foreach ($galleryImages as $image) { ?>
            <a class="gallery-image-hld" data-fancybox="gallery" href="<?php echo $block->escapeHtml($image) ?>">
                <img class="gallery-image" src="<?php echo $block->escapeHtml($image->resize(200)) ?>" alt="" />
            </a>
        <?php } ?>
    </div>
    <script>
    require(['jquery', 'domReady!'], function($){
        /* Deferer fancybox css loading */
        $("head").append($("<link rel='stylesheet' href='<?php echo $block->getViewFileUrl("Designnbuy_Background::css/jquery.fancybox.min.css") ?>' type='text/css' media='screen' />"));
        /* Deferer fancybox js loading */
        require(['Designnbuy_Background/js/jquery.fancybox.min'], function(){});
    });
</script>
<?php } ?>