<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Background background view template
 *
 * @var $block \Designnbuy\Background\Block\Background\View
 */
?>
<?php
    $_background = $this->getBackground();
    $_backgroundUrl = $_background->getBackgroundUrl();
    $_backgroundName = $block->escapeHtml($_background->getTitle(), null, true);
?>
<div class="background-view">
    <div class="background-holder background-holder-<?php echo $_background->getId() ?>">
        <div class="background-header clearfix">
            <?php echo $this->getInfoHtml() ?>
        </div>

        <div class="background-content">
            <div class="background-description clearfix">
                <?php if ($featuredImage = $_background->getImage()) { ?>
                <div class="background-ftimg-hld">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_backgroundName ?>" />
                </div>
                <?php } ?>
                <div class="background-text-hld">
                    <?php echo $block->getContent() ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>

        <div class="background-bottom">
            <?php echo $this->getChildHtml('background.background.bottom') ?>
        </div>
    </div>
</div>