<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Designnbuy\Customer\Block\Design */
?>
<?php $_designs = $block->getDesigns(); ?>
<?php echo $block->getChildHtml('info');?>
<?php if ($_designs->getSize()): ?>
    <div class="table-wrapper returns">
        <table class="data table gift-summary table-returns" id="my-returns-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('My Designs') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Design') ?>#</th>
                <th scope="col" class="col name"><?php /* @escapeNotVerified */ echo __('Name') ?></th>
                <th scope="col" class="col image"><?php /* @escapeNotVerified */ echo __('Image') ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php $_odd = ''; ?>
            <?php foreach ($_designs as $_design): ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Design #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $_design->getDesignId() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Name')) ?>" class="col name"><?php /* @escapeNotVerified */ echo $_design->getDesignName() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Image')) ?>" class="col image">
                        <?php
                        $pngs = $_design->getPng();
                        $images = explode(',', $pngs);
                        ?>
                        <div class="design-images" >
                            <?php foreach($images as $image):?>
                                <?php if($block->getImageUrl($image)): ?>
                                    <a href="#"  tabindex="-1" class="product-item-photo">
                                        <span class="design-image-container">
                                                <img class="design-image-photo " src="<?php echo $block->getImageUrl($image); ?>" alt="">
                                        </span>
                                    </a>
                                <?php endif;?>
                            <?php endforeach;?>
                        </div>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Edit')) ?>" class="col actions">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_design) ?>" class="action action-edit"><span><?php /* @escapeNotVerified */ echo __('View Design') ?></span></a>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Delete')) ?>" class="col actions">
                        <a href="#" class="action action-delete" data-post='<?= /* @escapeNotVerified */ $block->getDeletePostJson($_design) ?>'>
                            <span><?php /* @escapeNotVerified */ echo __('Delete') ?></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom">
            <?php echo $block->getPagerHtml(); ?>
        </div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have no designs.'); ?></span></div>
<?php endif ?>
