<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Designidea designidea list lazyload template
 *
 * @var $block \Designnbuy\Designidea\Block\Designidea\DesignideaList\Toolbar\Pager
 */
?>
<?php if ($block->useLazyload()) { ?>
    <?php
        $config = $block->getLazyloadConfig([
            'trigger_element' => '.mbdesignidea-lazyload-trigger'
        ]);
    ?>
    <div class="dnbdesignidea-autoloader" data-mage-init='{"<?php echo $block->getLazyloadJs() ?>" : <?php echo $config ?>}'>
    	<button class="mbdesignidea-lazyload-trigger dnbdesignidea-hide-onload action primary" title="<?php echo __('See more') ?>" type="button">
            <span><?php echo __('See more') ?></span>
        </button>
        <img class="designideas-loader dnbdesignidea-show-onload" src="<?php echo $block->getViewFileUrl('images/loader-2.gif') ?>" alt="<?php echo __('Editable Artwork loader') ?>" />
    </div>
<?php } ?>