<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Designidea designidea view template
 *
 * @var $block \Designnbuy\Designidea\Block\Designidea\View
 */
?>
<?php
    $_designidea = $this->getDesignidea();
    $_designideaUrl = $_designidea->getDesignideaUrl();
    $_designideaName = $block->escapeHtml($_designidea->getTitle(), null, true);
?>
<div class="designidea-view">
    <div class="designidea-holder designidea-holder-<?php echo $_designidea->getId() ?>">
        <div class="designidea-header clearfix">
            <?php echo $this->getInfoHtml() ?>
        </div>

        <div class="designidea-content">
            <div class="designidea-description clearfix">
                <?php if ($featuredImage = $_designidea->getImage()) { ?>
                <div class="designidea-ftimg-hld">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_designideaName ?>" />
                </div>
                <?php } ?>
                <div class="designidea-text-hld">
                    <?php echo $block->getContent() ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>

        <div class="designidea-bottom">
            <?php echo $this->getChildHtml('designidea.designidea.bottom') ?>
        </div>
    </div>
</div>