<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Background category info template
 *
 * @var $block \Designnbuy\Background\Block\Category\Info
 */
?>

<?php if ($content = $this->getContent()): ?>
    <div class="category-content"><?php echo $content ?></div>
<?php endif; ?>
