<?php
/**
 * Copyright © BrainActs Commerce OÜ. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \BrainActs\SalesRepresentative\Block\Adminhtml\Customer\Edit\AssignRepresentative $block */

/** @var \BrainActs\SalesRepresentative\Block\Adminhtml\Customer\Edit\Tab\MemberGrid $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>

<?php  echo $block->getGridHtml();?>
<input type="hidden" name="customer_members" id="in_customer_members" data-form-part="customer_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "BrainActs_SalesRepresentative/assign-member": {
                "selectedMembers": <?php /* @escapeNotVerified */ echo $block->getMemberJson(); ?>,
                "gridJsObjectName": <?php /* @escapeNotVerified */ echo '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
