<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Designnbuy\OrderTicket\Block\Adminhtml\OrderTicket\Create\Form */ ?>
<form id="edit_form" action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <?php echo $block->getChildHtml('orderticket_create_order') ?>

</form>
