<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var \Lof\RequestForQuote\Block\Adminhtml\Quote\View\Info $block
 */
$_order = $block->getOrder()



 ?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
                <th  style="width: 180px;"><?php echo __('Image'); ?></th>
                <?php $i = 0;
                $columns = $block->getColumns();
                $lastItemNumber = count($columns) ?>
                <?php foreach ($columns as $columnName => $columnTitle):?>
                    <?php if ($columnName == 'product') { ?>
                    <?php $i++; ?>
                    <th class="col-<?php /* @noEscape */ echo $columnName ?><?php /* @noEscape */ echo ($i === $lastItemNumber ? ' last' : '')?>"><span><?php /* @noEscape */ echo $columnTitle ?></span></th>
                    <?php } ?>
                <?php endforeach; ?>
                <th style="width: 180px;"><?php echo __('Attachment'); ?></th>
                <th style="width: 180px;"><?php echo __('Cost Price'); ?></th>
                <th style="width: 180px;"><?php echo __('Original Price'); ?></th>
                <th style="width: 180px;"><?php echo __('Price'); ?></th>
                <th style="width: 180px;"><?php echo __('Qty'); ?></th>
                <th style="width: 180px;"><?php echo __('Discount'); ?></th>
                <th style="width: 180px;"><?php echo __('Row Total (Incl. Tax)'); ?></th>
                <th style="width: 180px;"><?php echo __('GP Margin'); ?></th>
            </tr>
        </thead>
        <?php $_items = $block->getItemsCollection(); ?>
        <?php $i = 0; foreach ($_items as $_item):
        ?>

        <?php if ($_item->getParentItem()) {
            continue;
        } else {
            $i++;
        }?>
        <tbody class="<?php /* @noEscape */ echo $i%2 ? 'even' : 'odd' ?>">
            <?php echo $block->getItemHtml($_item) ?>
            <?php echo $block->getItemExtraInfoHtml($_item) ?>
        </tbody>
    <?php endforeach; ?>
</table>
</div>
