<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/**
 * @see \Designnbuy\OrderTicket\Block\Adminhtml\OrderTicket\Edit\Tab\General
 */
?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Account &amp; Order Information') ?></span>
    </div>
    <div class="admin__page-section-content">
        <?php echo $block->getChildHtml('request_details') ?>

        <?php //echo $block->getChildHtml('shipping_method') ?>
    </div>
</section>

<!--<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /*//echo __('Address Information') */?></span>
    </div>

    <div class="admin__page-section-content">
        <?php /*//echo $block->getChildHtml('shipping_address') */?>

        <?php /*//echo $block->getChildHtml('return_address') */?>
    </div>
</section>-->

<section class="admin__page-section">

    <div class="admin__page-section-content">
        <?php echo $block->getChildHtml('comments_history') ?>
    </div>
</section>
