<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div id="orderticket_reason_container" class="orderticket-popup" style="display:none">
    <div class="popup-window-wrapper">
        <div class="popup-window-title">
            <div class="title">
                <?php /* @escapeNotVerified */ echo __('Reason to Order Ticket') ?>
            </div>
        </div>
        <div id="orderticket_reason_content" class="popup-window-content"></div>
        <div class="popup-window-buttons-set">
            <button class="action-save action-secondary ok_button" type="button">
                <span><?php /* @escapeNotVerified */ echo __('OK') ?></span>
            </button>
        </div>
    </div>
</div>
