<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Designnbuy\OrderTicket\Block\Adminhtml\OrderTicket\Edit\Tab\General\History" */
?>
<div class="admin__page-section-item order-comments-history" id="orderticket-history-block">
    <div class="admin__page-section-item-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Order Ticket History') ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <div id="history_form" class="orderticket-history-form edit-order-comments">
            <div class="admin__field">
                <label for="comment_status" class="admin__field-label"><?php /* @escapeNotVerified */ echo __('Status') ?></label>
                <div class="admin__field-control">
                    <select name="comment[status]" id="comment_status" class="admin__control-select">
                        <?php foreach ($block->getStatuses() as $_code => $_label): ?>
                            <option value="<?php /* @escapeNotVerified */ echo $_code ?>"><?php /* @escapeNotVerified */ echo $_label ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="admin__field">
                <label class="admin__field-label" for="history_comment">
                    <span><?php /* @escapeNotVerified */ echo __('Comment Text') ?></span></label>
                <div class="admin__field-control">
                    <textarea name="comment[comment]"
                        class="admin__control-textarea"
                        rows="3"
                        cols="5"
                        id="history_comment"></textarea>
                </div>
            </div>
            <div class="admin__field">
                <label class="admin__field-label"
                       for="file"><?php /* @escapeNotVerified */ echo __('File') ?></label>
                <div class="upload-wrapper" data-bind="scope: 'uploader'" data-mage-init='{
                               "Magento_Ui/js/core/app": {
                                   "components": {
                                       "uploader": {
                                            "formElement" : "fileUploader",
                                            "componentType" : "fileUploader",
                                           "component": "Magento_Ui/js/form/element/file-uploader",
                                           "template": "Designnbuy_OrderTicket/components/file-uploader",
                                           "inputName": "ticket",
                                           "name": "ticket",
                                           "fileInputName": "ticket",
                                           "isMultipleFiles": false,
                                           "uploaderConfig": {
                                                "url": "<?php echo $block->getUrl('adminhtml/*/upload'); ?>"
                                           }
                                       }
                                   }
                                }
                            }
                        '>
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
            </div>
            <div class="admin__field admin__field-option">
                <?php if ($block->canSendCommentEmail()): ?>
                    <div class="admin__field admin__field-option">
                        <input name="comment[is_customer_notified]"
                               class="admin__control-checkbox"
                               type="checkbox"
                               id="history_notify"
                               value="1"/>
                        <label class="admin__field-label"
                               for="history_notify">
                            <?php /* @escapeNotVerified */ echo __('Notify Customer by Email') ?></label>
                    </div>
                <?php endif; ?>
                <input name="comment[is_visible_on_front]"
                       class="admin__control-checkbox"
                       type="checkbox"
                       id="history_visible"
                       value="1" />
                <label class="noorderticketl admin__field-label"
                       for="history_visible">
                    <span><?php echo __('Visible on Storefront') ?></span></label>
            </div>
        </div>
    </div>
</div>
