<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Color sidebar recent colors template
 *
 * @var $block \Designnbuy\Color\Block\Sidebar\Recent
 */
?>

<?php
    $_colorCollection = $block->getColorCollection();
?>
<?php if ($_colorCollection->count()) { ?>
<div class="widget block block-recent-colors" data-bind="scope: 'recemt-colors'">
    <div class="block-title">
        <strong><?php echo __('Recent Colors') ?></strong>
    </div>
    <div class="block-content">
        <?php foreach ($_colorCollection as $_color) { ?>
            <div class="item">
                <a class="color-item-link"
                   href="<?php echo $_color->getColorUrl() ?>">
                    <?php echo $block->escapeHtml($_color->getTitle()) ?>
                </a>
            </div>

        <?php } ?>
    </div>
</div>
<?php } ?>