<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Background recent backgrounds widget
 *
 * @var $block \Designnbuy\Background\Block\Widget\Recent
 */
?>

<?php
    $_backgroundCollection = $block->getBackgroundCollection();
?>
<?php if ($_backgroundCollection->count()) { ?>
<div class="background-list-wrapper background-widget-recent background-widget-recent-masonry">
    <h3 class="title"><?php echo $block->escapeHtml($block->getTitle()) ?></h3>
    <ul class="background-list clearfix">
        <?php foreach ($_backgroundCollection as $_background) { ?>
            <?php
                $_backgroundUrl = $_background->getBackgroundUrl();
                $_backgroundName = $block->escapeHtml($_background->getTitle(), null, true);
            ?>
            <li class="background-holder background-holder-<?php echo $_background->getId() ?>">
                <div class="background-header">

                    <div class="background-title-holder clearfix">
                        <div class="background-title">
                            <a class="background-item-link"
                               href="<?php echo $_backgroundUrl ?>">
                                <?php echo $_backgroundName; ?>
                            </a>
                        </div>
                    </div>

                    <div class="background-info clear">
                        <div class="item background-posed-date">
                            <span class="label"><?php echo __('Backgrounded:') ?></span>
                            <span class="value"><?php echo $_background->getPublishDate('F d, Y') ?></span>
                        </div>
                        <?php if ($_categoriesCount = $_background->getCategoriesCount()) { ?>
                        <div class="dash">|</div>
                        <div class="item background-categories">
                            <span class="label"><?php echo __('Categories:') ?></span>
                            <?php $n = 0; foreach($_background->getParentCategories() as $ct) { $n++; ?>
                                <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
                                <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
                            <?php } ?>
                        </div>
                        <?php } ?>
                    </div>
                </div>

                <div class="background-content">
                    <div class="background-description clearfix">
                        <?php if ($featuredImage = $_background->getImage()) { ?>
                        <div class="background-ftimg-hld">
                            <a href="<?php echo $_backgroundUrl ?>" title="<?php echo $_backgroundName ?>">
                                <img src="<?php echo $featuredImage ?>" alt="<?php echo $_backgroundName ?>" />
                            </a>
                        </div>
                        <?php } ?>
                        <?php if ($content = $block->getShorContent($_background)) { ?>
                            <div class="background-text-hld clearfix">
                                <?php echo $content ?>
                            </div>
                        <?php } ?>
                        <a class="background-read-more" href="<?php echo $_backgroundUrl ?>" title="<?php echo $_backgroundName ?>">
                           <?php echo __('Read more &#187;') ?>
                        </a>
                    </div>
                </div>
                <div class="background-footer">

                </div>
            </li>

        <?php } ?>
    </ul>
</div>
<script>
requirejs( [ 'require', 'jquery', 'Designnbuy_Background/js/lib/masonry.pkgd.min' ],
function( require, $, Masonry ) {
    require( [ 'jquery-bridget/jquery-bridget' ],
    function( jQueryBridget ) {
        jQueryBridget( 'masonry', Masonry, $ );
        $('.background-list').masonry({
            itemSelector: '.background-holder',
            percentPosition: true
        })
    });
});
<?php /* more info http://masonry.desandro.com/extras.html */ ?>
</script>

<?php } ?>