<?php
/**
 * Copyright © BrainActs Commerce OÜ. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \BrainActs\SalesRepresentative\Block\Adminhtml\Member\AssignCustomers $block */

/** @var \BrainActs\SalesRepresentative\Block\Adminhtml\Tab\Customer $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>

<?php  echo $block->getGridHtml();?>
<input type="hidden" name="member_customers" id="in_member_customers" data-form-part="salesrep_member_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "BrainActs_SalesRepresentative/assign-customers": {
                "selectedCustomers": <?php /* @escapeNotVerified */ echo $block->getCustomersJson(); ?>,
                "gridJsObjectName": <?php /* @escapeNotVerified */ echo '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>