<?php
/**
 * Copyright © BrainActs Commerce OÜ. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \BrainActs\SalesRepresentative\Block\Adminhtml\Dashboard\Graph $block */
?>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div class="dashboard-diagram">
    <div class="dashboard-diagram-switcher">
        <label for="order_<?= $block->getHtmlId() ?>_period" class="label"><?= /* @escapeNotVerified */
            __('Select Range:') ?></label>
        <select name="period" id="<?= $block->getHtmlId() ?>_period"  class="admin__control-select" data-url="<?php echo $block->getRequestUrl()?>">
            <?php foreach ($this->helper('Magento\Backend\Helper\Dashboard\Data')->getDatePeriods() as $value => $label): ?>
                <?php if (in_array($value, ['custom', '24h','2y'])) {
                    continue;
                } ?>
                <option value="<?= /* @escapeNotVerified */
                $value ?>"
                    <?php if ($block->getRequest()->getParam('period') == $value): ?> selected="selected"<?php endif; ?>
                ><?= /* @escapeNotVerified */
                    $label ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div id="chart"></div>
</div>

<script type="text/javascript">

    google.charts.load('current', {'packages': ['corechart', 'line']});
    google.charts.setOnLoadCallback(drawChart);
    var chart = null;
    var dataV = null;
    var optionsV = null;
    function drawChart() {
        var reportData = <?php echo $block->prepareReportData()?>;
        dataV = new google.visualization.DataTable();
        dataV.addColumn('date', 'Period');
        dataV.addColumn('number', 'Amount, $');
        optionsV = {
            chartArea: {width: '100%', height: '100%'},
            legend: {position: 'none'},
            width: 500,
            height: 380,
            colors: ['#ee5c20'],
            hAxis: {
                title: 'Year',
                slantedText: true,
                slantedTextAngle: 45,
                textStyle: {
                    fontSize: 10
                }
            }
        };

        dataV.addRows(reportData.length+1);

        jQuery.each(reportData, function(index, item){
            dataV.setCell(index, 0, new Date(item[0]));
            dataV.setCell(index, 1, item[1]);
        });


        chart = new google.charts.Line(document.getElementById('chart'));
        chart.draw(dataV, google.charts.Line.convertOptions(optionsV));
    }
</script>