<?php
/**
 * Designtool template Iframe
 *
 * @var $block \Designnbuy\Designidea\Block\Adminhtml\Designidea\Create
 */
?>

<iframe id="designtool_iframe" name="Design N Buy" src="<?php echo $block->getIframeUrl(); ?>" width="100%" height="750px" frameborder="0" ></iframe>
<script type="application/javascript">
    jQuery('body').trigger('processStart');

    jQuery(document).ready(function() {
        jQuery('#designtool_iframe').on('load', function () {
            jQuery('body').trigger('processStop');
        });
    });
</script>