<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Template template view template
 *
 * @var $block \Designnbuy\Template\Block\Template\View
 */
?>
<?php
    $_template = $this->getTemplate();
    $_templateUrl = $_template->getTemplateUrl();
    $_templateName = $block->escapeHtml($_template->getTitle(), null, true);
?>
<div class="template-view">
    <div class="template-holder template-holder-<?php echo $_template->getId() ?>">
        <div class="template-header clearfix">
            <?php echo $this->getInfoHtml() ?>
        </div>

        <div class="template-content">
            <div class="template-description clearfix">
                <?php if ($featuredImage = $_template->getImage()) { ?>
                <div class="template-ftimg-hld">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_templateName ?>" />
                </div>
                <?php } ?>
                <div class="template-text-hld">
                    <?php echo $block->getContent() ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>

        <div class="template-bottom">
            <?php echo $this->getChildHtml('template.template.bottom') ?>
        </div>
    </div>
</div>