<div class="admin__field">
<div class="admin__field-control">
<ul class="messages">
    <li style="margin-top:11px;" class="notice-msg">
        <ul style="list-style-type:none">
            <li>1. To create JS Font file <a href="http://convertfonts.designnbuy.us/generate/" target="_base">click here</a>.</li>
            <li>2. Follow the instructions on the web page.</li>
            <li>3. Find "Customization (for 3rd-party scripts only)" section, replace "Cufon.registerFont" with "Raphael.registerFont". Like the image below<br><img src="https://rightwaysolution.in/cufon/cufon_instruction.jpg" alt="in Customization (for 3rd-party scripts only) section, replace Cufon.registerFont with Raphael.registerFont">
            </li>
        </ul>
    </li>
</ul>
</div>
</div>