<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */;
?>
<div class="message message-notice notice">
    <div data-ui-id="messages-message-notice">
        <p class="fontrswf">How to import font?</p>
        <ul class="listul">
            <li><span>Download the
                    <label class="addafter" for="entity">
                        <span id="sample-file-span" class="no-display" style="display: inline;">
                            <a id="sample-file-link" href="<?php /* @escapeNotVerified */ echo $block->getUrl('*/import/download/') ?>">Sample File</a>
                        </span>
                    </label>
                    and edit the as per your need to import the font.</span></li>
            <li><span>You also need to upload all required font files in  the  "pub/media/designnbuy/font/" folder.</span></li>
            <br>
            <span>Note: File must be in "csv" extenstion and set the all fonts permission to 777</span>
        </ul>
    </div>
</div>
