<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Template recent templates widget
 *
 * @var $block \Designnbuy\Template\Block\Widget\Recent
 */
?>

<?php
    $_templateCollection = $block->getTemplateCollection();
?>
<?php if ($_templateCollection->count()) { ?>
<div class="template-list-wrapper template-widget-recent">
    <h3 class="title"><?php echo $block->escapeHtml($block->getTitle()) ?></h3>
    <ul class="template-list clearfix">
        <?php foreach ($_templateCollection as $_template) { ?>
            <?php
                $_templateUrl = $_template->getTemplateUrl();
                $_templateName = $block->escapeHtml($_template->getTitle(), null, true);
            ?>
            <li class="template-holder template-holder-<?php echo $_template->getId() ?>">
                <div class="template-header">

                    <div class="template-title-holder clearfix">
                        <div class="template-title">
                            <a class="template-item-link"
                               href="<?php echo $_templateUrl ?>">
                                <?php echo $_templateName; ?>
                            </a>
                        </div>
                    </div>

                    <div class="template-info clear">
                        <div class="item template-posed-date">
                            <span class="label"><?php echo __('Templateed:') ?></span>
                            <span class="value"><?php echo $_template->getPublishDate('F d, Y') ?></span>
                        </div>
                        <?php if ($_categoriesCount = $_template->getCategoriesCount()) { ?>
                        <div class="dash">|</div>
                        <div class="item template-categories">
                            <span class="label"><?php echo __('Categories:') ?></span>
                            <?php $n = 0; foreach($_template->getParentCategories() as $ct) { $n++; ?>
                                <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
                                <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
                            <?php } ?>
                        </div>
                        <?php } ?>
                    </div>
                </div>

                <div class="template-content">
                    <div class="template-description clearfix">
                        <?php if ($featuredImage = $_template->getImage()) { ?>
                        <div class="template-ftimg-hld">
                            <a href="<?php echo $_templateUrl ?>" title="<?php echo $_templateName ?>">
                                <img src="<?php echo $featuredImage ?>" alt="<?php echo $_templateName ?>" />
                            </a>
                        </div>
                        <?php } ?>
                        <div class="template-text-hld clearfix">
                            <?php echo $block->getShorContent($_template) ?>
                        </div>
                        <a class="template-read-more" href="<?php echo $_templateUrl ?>" title="<?php echo $_templateName ?>"
                           >
                           <?php echo __('Read more &#187;') ?>
                        </a>
                    </div>
                </div>
                <div class="template-footer">

                </div>
            </li>

        <?php } ?>
    </ul>
</div>
<?php } ?>