<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Color color list item template
 *
 * @var $block \Designnbuy\Color\Block\Color\AbstractColor
 */
?>
<?php
    $_color = $this->getColor();
    $_colorUrl = $_color->getColorUrl();
    $_colorName = $block->escapeHtml($_color->getTitle(), null, true);
?>
<li class="color-holder color-holder-<?php echo $_color->getId() ?>">
    <div class="color-header">

        <div class="color-title-holder clearfix">
            <h2 class="color-title">
                <a class="color-item-link"
                   href="<?php echo $_colorUrl ?>">
                    <?php echo $_colorName; ?>
                </a>
            </h2>
        </div>

        <?php echo $this->getInfoHtml() ?>
    </div>

    <div class="color-content">
        <div class="color-description clearfix">
            <?php if ($featuredImage = $_color->getImage()) { ?>
            <div class="color-ftimg-hld">
                <a href="<?php echo $_colorUrl ?>" title="<?php echo $_colorName ?>">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_colorName ?>" />
                </a>
            </div>
            <?php } ?>
            <div class="color-text-hld clearfix">
                <?php echo $block->getShorContent() ?>
            </div>
            <a class="color-read-more" href="<?php echo $_colorUrl ?>" title="<?php echo $_colorName ?>"
               >
               <?php echo __('Read more &#187;') ?>
            </a>
        </div>
    </div>
    <div class="color-footer">

    </div>
</li>