<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Font available for import template
 *
 * @var $block \Magento\Backend\Block\Template
 */
?>
<script type="text/javascript">
    var products = ["1","2","3","4","5","10"];
</script>
<form id="design_form" name="design_form">
    <button type="button"
            title="<?php /* @escapeNotVerified */ echo "save" ?>"
            id="save"
            class="action tocart primary">
        <span><?php /* @escapeNotVerified */ echo "save" ?></span>
    </button>
</form>
<?php //echo $block->getChildHtml('ajay_note_note_index')?>
<script>
    require([
        'jquery',
        'mage/mage',
        'uiRegistry',
        'underscore'
    ], function ($) {
        'use strict';
        var buttonpressed;
        $('#save').on('click', function(event){
            var registry = require('uiRegistry');
            var listing = registry.get('name = ajay_note_note_index.ajay_note_note_index.ajay_note_note_columns.ids');

            if (_.isUndefined(listing)) {
                return;
            }
            console.log('listing',listing);
            var selections = listing.getSelections();
            console.log('selections.selected',selections.selected);
        })
    });
</script>
