<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $block->getProduct(); ?>
<?php

?>
<div class="product-add-form product-actions-info">
    <form data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
          action="<?= /* @NoEscape */ $block->getSubmitUrl($_product) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $_product->getId() ?>" />
        <input type="hidden" name="pagename" value="<?= $block->getRequest()->getModuleName().'_'.$block->getRequest()->getControllerName().'_'.$block->getRequest()->getActionName(); ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <input type="hidden" name="item"  value="<?= /* @noEscape */ $block->getRequest()->getParam('id') ?>" />
        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getChildHtml('form_top') ?>
        <div class="product-actions-info-content">
            <?php if (!$block->hasOptions()):?>
                <?= $block->getChildHtml('product_info_form_content') ?>
            <?php else:?>
                
                <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'):?>
                    <?= $block->getChildChildHtml('options_container') ?>
                <?php endif;?>
            <?php endif; ?>

            <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'):?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
            <?= $block->getChildHtml('form_bottom') ?>
    
        </div>
    </form>
</div>
<script>
    require([
        'jquery',
        'priceBox'
    ], function($){
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?= $block->escapeHtml($_product->getId()) ?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>});
    });
</script>

<style type="text/css">
    .price-container span.price-wrapper:before {
        content: '(Excl. Vat) ';
        float: left;
        padding-right: 5px;
        /*font-size: 18px !important;*/
    }
</style>