<?php
// @codingStandardsIgnoreFile
?>
<div>
    <div>
        <?php echo $this->getChildHtml('weltpixelContactPage'); ?>
    </div>
    <div>
        <div>
            <h3 style="margin-bottom: 10px;"><?php /* @escapeNotVerified */ echo __('Contact Us') ?></h3>
        </div>
        <form style="width:100%; max-width:400px; min-width:300px; margin-top:0px;"
              action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
              id="contact-form"
              method="post"
              data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
				<div class="field subject required">
					<h4 style="margin-top:0px;">Reason for contacting us</h4>
					<div class="control">
						Request a quote<input style="margin-left:10px; margin-right:20px;" id="subject" value="Request a quote" name="subject"  title="<?php /* @escapeNotVerified */ ?>" value=""  type="radio" data-validate="{required:false}"/> 
						Suggest a new product<input style="margin-left:10px; margin-right:20px;" id="subject" name="subject" value="Suggest a new product" title="<?php /* @escapeNotVerified */ ?>" value="" type="radio" data-validate="{required:false}"/><br>
						Give some feedback<input style="margin-left:10px; margin-right:20px;" id="subject" name="subject" value="Give some feedback" title="<?php /* @escapeNotVerified */ ?>" value="" type="radio" data-validate="{required:false}"/>
						Other<input style="margin-left:10px;" id="subject" name="subject" value="Other" title="<?php /* @escapeNotVerified */ ?>" value="" type="radio" data-validate="{required:false}"/>
					</div>
				</div>
                <div class="field name required">
                    <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
                    <div class="control">
                        <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                    <div class="control">
                        <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="field telephone">
                    <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
                    <div class="control">
                        <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
                    </div>
                </div>
                <div class="field comment required">
                    <label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?></span></label>
                    <div class="control">
                        <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                    </div>
                </div>
                <?php echo $block->getChildHtml('form.additional.info'); ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <input type="hidden" name="hideit" id="hideit" value="" />
                    <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                        <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>