<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */;
?>
<div class="message message-notice notice">
    <div data-ui-id="messages-message-notice">
        <p>How to import color?</p>
        <ul>
            <li><span>Download the
                    <label class="addafter" for="entity">
                        <span id="sample-file-span" class="no-display" style="display: inline;">
                            <a id="sample-file-link" href="<?php /* @escapeNotVerified */ echo $block->getUrl('*/import/download/') ?>">Sample File</a>
                        </span>
                    </label>
                    and edit the as per your need to import the color.</span></li>
        </ul>
    </div>
</div>
