<?php
/**
 * @author Drc Systems India Pvt Ltd.
*/

?>
<div class="import-export-tax-rates">
    <div class="import-tax-rates">
        <form id="import-form" class="admin__fieldset" action="<?php /* @escapeNotVerified */ 
        echo $block->getUrl('drc_storepickup/import/save') ?>" method="post" enctype="multipart/form-data">
            <?php echo $block->getBlockHtml('formkey')?>
            <div class="fieldset admin__field">
                <label for="import_storelocations_file" class="admin__field-label"><span>
                	<?php /* @escapeNotVerified */ echo __('Import Storelocations') ?></span></label>
                <div class="admin__field-control">
                    <input type="file" id="import_storelocations_file" name="import_storelocations_file"  data-validate="{required:true}"
                    class="input-file required-entry"/>
                    <input type="submit" value="submit" />
                </div>
            </div>
        </form>
    </div>
</div>
