<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="footer-top-newsletter newsletter-subscribe">
    <form class="form subscribe"
        novalidate
        action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
        method="post"
        data-mage-init='{"validation": {"errorClass": "mage-error"}}'
        id="newsletter-validate-detail">
        <div class="d-flex">
            <div class="table-col col-md-4 col-sm-12 col-xs-12">
                <h2><?= $block->escapeHtml(__('Newsletter')) ?></h2>
                <p><?= $block->escapeHtml(__('sign up for exclusive updates, new arrivals and insider-only discounts')) ?></p>
            </div>
            <div class="table-col col-md-8 col-sm-12 col-xs-12">
                <div class="form-group">
                    <input name="email" type="email" id="newsletter"
                           placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                           data-mage-init='{"mage/trim-input":{}}'
                           data-validate="{required:true, 'validate-email':true}"/>
                    <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                        <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
