<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Product related templates template
 *
 * @var $block \Designnbuy\Template\Block\Catalog\Product\RelatedTemplates
 */
?>
<?php 
//echo "<pre>"; print_r($block->getRequest()->getParams()); exit;
$params = $block->getRequest()->getParams();
unset($params['category_id']);
unset($params['width']);
unset($params['height']);
unset($params['p']);
unset($params['search']);

$product_params = json_encode($params);

?>
<?php $templates = []; ?>
<?php if ($block->displayTemplates()) { ?>
    <?php $_product = $block->getProduct(); ?>
    <?php $_templateCollection = $block->getTemplateCollection(); ?>
    <?php if ($_templateCollection->count()) { ?>
        <?php //$templates = $_templateCollection->getData(); ?>
        <div class="page-products wrapper grid products-grid templates-grid products-related" style="clear: both">
            <div class="block related template-container">
                <!-- <div class="block-title title">
                    <h3>
                        <span id="block-related-heading" role="heading"
                              aria-level="2"><?php //echo __('PLEASE CHOOSE A TEMPLATE TO CUSTOMIZE') ?></span>
                    </h3>
                </div> -->
                <form action="<?php echo $block->getBaseUrl(); ?>/checkout/cart/add" method="post" id="product_addtocart_form">
                    <input type="hidden" name="product_params" id="product_params" value='<?php echo $product_params; ?>'>
                </form>
                <div class="products wrapper grid products-grid">
                    <ul class="products list items product-items">
                        <?php foreach ($_templateCollection as $_template): $templates[] = $_template->getData();?><?php if (!$_template->getSvg()): continue; endif; ?><?php $_templateUrl = $this->helper('Designnbuy\Canvas\Helper\Data')->getTemplatePersonalisePageUrl($_product, $_template); ?>
                        
                        <li class="item product product-item template-item template-holder-<?php echo $_template->getId() ?>">
                            <div class="product-item-info" data-container="product-grid">
                                <?php if ($featuredImage = $_template->getImage()): ?>
                                <a class="product photo product-item-photo" href="javascript:void(0)" title="<?php echo $block->escapeHtml($_template->getTitle()); ?>">
                                    <span class="product-image-container" style="width: 240px;">
                                        <span class="product-image-wrapper" style="padding-bottom : <?php echo (298/240*100); ?>%">
                                            <img 
                                                src="<?php echo $featuredImage ?>"
                                                alt="<?php echo $block->escapeHtml($_template->getTitle()); ?>" 
                                                style="<?php echo ($_template->getHeight() > $_template->getWidth()) ? "height:100%;width:auto" : "height:auto;width:100%" ?>" 
                                                class="product-image-photo lazy"
                                            />
                                        </span>
                                    </span>
                                </a>
                                <?php endif; ?>
                                
                                <div class="product details product-item-details"><strong class="product name product-item-name"><a class="product-item-link" href="#"><?php echo $block->escapeHtml($_template->getTitle()); ?></a></strong>
                                    <div class="price-box">
                                        <div class="product actions">
                                            <div class="actions-primary">
                                                    <button type="submit" title="<?php /* @escapeNotVerified */ echo $block->escapeHtml($_template->getTitle()) ?>" class="action tocart primary template" data-mage-init='{ "Designnbuy_Canvas/js/customize": { "action": "<?php echo $block->escapeUrl($_templateUrl) ?>" } }'>
                                                        <span><?php /* @escapeNotVerified */ echo __('Personalize') ?></span>
                                                    </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <?php endforeach;  ?>
                    </ul>
                </div>
            </div>
            <?php echo $block->getChildHtml('pagination');?>
        </div>
        <div class="message-error error message template-error-message" style="display: none;" data-ui-id="message-error">
            <div><?php echo __('No Templates Found.') ?></div>
        </div>
        

    <?php } else { ?>
        <div class="page-products wrapper grid products-grid templates-grid products-related" style="clear: both">
            No Template Found
        </div>
    <?php } ?>
<?php } ?>
<?php
$option = $block->getSizeOption();
?>
<style type="text/css">
    .template-container   .product-image-photo {box-shadow: 3px 3px 4px 0 rgba(0, 0, 0, 0.3); border: 1px solid #bbbbbb;}
</style>


