<?php

namespace Designnbuy\Designidea\Model\Designidea;

use Designnbuy\Designidea\Model\Designidea;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use Magento\UrlRewrite\Model\OptionProvider;
use Magento\UrlRewrite\Model\UrlFinderInterface;
use Designnbuy\Designidea\Model\DesignideaUrlRewriteGenerator;
use Designnbuy\Designidea\Model\DesignideaUrlPathGenerator;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;
use Magento\Store\Model\StoreManagerInterface;

/**
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 */
class CurrentUrlRewritesRegenerator
{
    /** @var Designidea */
    protected $designidea;

    /** @var UrlFinderInterface */
    protected $urlFinder;

    /** @var DesignideaUrlPathGenerator */
    protected $designideaUrlPathGenerator;

    /** @var UrlRewriteFactory */
    protected $urlRewriteFactory;

    /**
     * @param UrlFinderInterface $urlFinder
     * @param DesignideaUrlPathGenerator $designideaUrlPathGenerator
     * @param UrlRewriteFactory $urlRewriteFactory
     */
    public function __construct(
        UrlFinderInterface $urlFinder,
        DesignideaUrlPathGenerator $designideaUrlPathGenerator,
        UrlRewriteFactory $urlRewriteFactory
    ) {
        $this->urlFinder = $urlFinder;
        $this->designideaUrlPathGenerator = $designideaUrlPathGenerator;
        $this->urlRewriteFactory = $urlRewriteFactory;
    }

    /**
     * Generate list based on current rewrites
     *
     * @param int $storeId
     * @param Designidea $designidea
     * @return UrlRewrite[]
     */
    public function generate($storeId, Designidea $designidea)
    {
        $this->designidea = $designidea;

        $currentUrlRewrites = $this->urlFinder->findAllByData(
            [
                UrlRewrite::STORE_ID => $storeId,
                UrlRewrite::ENTITY_ID => $this->designidea->getId(),
                UrlRewrite::ENTITY_TYPE => DesignideaUrlRewriteGenerator::ENTITY_TYPE,
            ]
        );

        $urlRewrites = [];
        foreach ($currentUrlRewrites as $currentUrlRewrite) {
            $url = $currentUrlRewrite->getIsAutogenerated()
                ? $this->generateForAutogenerated($currentUrlRewrite, $storeId)
                : $this->generateForCustom($currentUrlRewrite, $storeId);
            $urlRewrites = array_merge($urlRewrites, $url);
        }

        $this->designidea = null;
        return $urlRewrites;
    }

    /**
     * @param UrlRewrite $url
     * @param int $storeId
     * @return array
     */
    protected function generateForAutogenerated($url, $storeId)
    {
        if (!$this->designidea->getData('save_rewrites_history')) {
            return [];
        }
        $targetPath = $this->designideaUrlPathGenerator->getUrlPathWithSuffix($this->designidea, $storeId);
        if ($url->getRequestPath() === $targetPath) {
            return [];
        }
        return [
            $this->urlRewriteFactory->create()
                ->setEntityType(DesignideaUrlRewriteGenerator::ENTITY_TYPE)
                ->setEntityId($this->designidea->getId())
                ->setRequestPath($url->getRequestPath())
                ->setTargetPath($targetPath)
                ->setRedirectType(OptionProvider::PERMANENT)
                ->setStoreId($storeId)
                ->setDescription($url->getDescription())
                ->setIsAutogenerated(0)
                ->setMetadata($url->getMetadata())
        ];
    }

    /**
     * @param UrlRewrite $url
     * @param int $storeId
     * @return array
     */
    protected function generateForCustom($url, $storeId)
    {
        $targetPath = $url->getRedirectType()
            ? $this->designideaUrlPathGenerator->getUrlPathWithSuffix($this->designidea, $storeId)
            : $url->getTargetPath();
        if ($url->getRequestPath() === $targetPath) {
            return [];
        }
        return [
            $this->urlRewriteFactory->create()
                ->setEntityType(DesignideaUrlRewriteGenerator::ENTITY_TYPE)
                ->setEntityId($this->designidea->getId())
                ->setRequestPath($url->getRequestPath())
                ->setTargetPath($targetPath)
                ->setRedirectType($url->getRedirectType())
                ->setStoreId($storeId)
                ->setDescription($url->getDescription())
                ->setIsAutogenerated(0)
                ->setMetadata($url->getMetadata())
        ];
    }
}
