<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Color color info template
 *
 * @var $block \Designnbuy\Color\Block\Color\Info
 */
?>

<?php $_color = $block->getColor() ?>

<div class="color-info clear">
    <div class="item color-posed-date">
        <span class="label"><?php echo __('Colored:') ?></span>
        <span class="value"><?php echo $_color->getPublishDate('F d, Y') ?></span>
    </div>
    <?php if ($_categoriesCount = $_color->getCategoriesCount()) { ?>
    <div class="dash">|</div>
    <div class="item color-categories">
        <span class="label"><?php echo __('Categories:') ?></span>
        <?php $n = 0; foreach($_color->getParentCategories() as $ct) { $n++; ?>
            <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>">
                <?php echo $block->escapeHtml($ct->getTitle()) ?>
            </a>
            <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
        <?php } ?>
    </div>
    <?php } ?>
    <?php if ($_tagsCount = $_color->getTagsCount()) { ?>
    <div class="dash">|</div>
    <div class="item color-categories">
        <span class="label"><?php echo __('Tags:') ?></span>
        <?php $n = 0; foreach($_color->getRelatedTags() as $tag) { $n++; ?>
            <a title="<?php echo $block->escapeHtml($tag->getTitle()) ?>" href="<?php echo $tag->getTagUrl() ?>">
                <?php echo $block->escapeHtml($tag->getTitle()) ?>
            </a>
            <?php if ($n != $_tagsCount) { ?>, <?php } ?>
        <?php } ?>
    </div>
    <?php } ?>
    <?php if ($block->authorEnabled()) { ?>
        <?php if ($_author = $_color->getAuthor()) { ?>
        <div class="dash">|</div>
        <div class="item color-author">
            <span class="label"><?php echo __('Author:') ?></span>
            <span class="value">
                <?php if ($authorPageEnabled = $block->authorPageEnabled()) { ?>
                <a title="<?php echo $block->escapeHtml($_author->getTitle()) ?>" href="<?php echo $_author->getAuthorUrl() ?>">
                <?php } ?>
                    <?php echo $block->escapeHtml($_author->getTitle()) ?>
                <?php if ($authorPageEnabled) { ?>
                </a>
                <?php } ?>
            </span>
        </div>
        <?php } ?>
    <?php } ?>
</div>