<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Color color view template
 *
 * @var $block \Designnbuy\Color\Block\Color\View
 */
?>
<?php
    $_color = $this->getColor();
    $_colorUrl = $_color->getColorUrl();
    $_colorName = $block->escapeHtml($_color->getTitle(), null, true);
?>
<div class="color-view">
    <div class="color-holder color-holder-<?php echo $_color->getId() ?>">
        <div class="color-header clearfix">
            <?php echo $this->getInfoHtml() ?>
        </div>

        <div class="color-content">
            <div class="color-description clearfix">
                <?php if ($featuredImage = $_color->getImage()) { ?>
                <div class="color-ftimg-hld">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_colorName ?>" />
                </div>
                <?php } ?>
                <div class="color-text-hld">
                    <?php echo $block->getContent() ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>

        <div class="color-bottom">
            <?php echo $this->getChildHtml('color.color.bottom') ?>
        </div>
    </div>
</div>