<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Designnbuy\DesignReview\Block\Product\View\Other $block */
?>
<?php $_product = $block->getProduct(); ?>
<div class="actions">
    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="action back"><span><?= $block->escapeHtml(__('Back to Main Product Info')) ?></span></a>
</div>
