<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Designidea related designideas template
 *
 * @var $block \Designnbuy\Designidea\Block\Designidea\View\RelatedDesignideas
 */
?>

<?php if ($block->displayDesignideas()) { ?>
    <?php $_designideaCollection = $block->getDesignideaCollection(); ?>
    <?php if ($_designideaCollection->count()) { ?>
    <div class="block related">
        <div class="block-title title">
            <strong id="block-relateddesignideas-heading" role="heading" aria-level="2">
                <?php echo __('Related Editable Artworks') ?>
            </strong>
        </div>
        <ol class="block-content">
            <?php foreach ($_designideaCollection as $_designidea) { ?>
                <li class="item">
                    <a class="designidea-item-link"
                       href="<?php echo $_designidea->getDesignideaUrl() ?>">
                        <?php echo $block->escapeHtml($_designidea->getTitle()); ?>
                    </a>
                </li>
            <?php } ?>
        </ol>
    </div>
    <?php } ?>
<?php } ?>