<?php  $_report = $block->getProductCommissionDashboard(); ?>
<table class="data-grid">
    <thead>
        <tr>
            <th class="data-grid-th" width="250px"><span><?php echo __('Report Dashboard'); ?></span></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr class="data-grid-tr-data">
            <td class="label"><?php echo __('Commission Report For');?></td>
            <td class="value"><b><?php echo $_report['data_for']; ?></b></td>
        </tr>               
        <tr>
            <td class="label"><?php echo __('Total Product Sales');?></td>
            <td class="value"><b><?php echo $_report['total_product_sold'];?></b></td>
        </tr>
        <tr>
            <td class="label"><?php echo __('Total Sales');?></td>
            <td class="value"><b><?php echo $block->setFormatedAmount($_report['total_commission_paid']); ?></b></td>
        </tr>
    </tbody>
</table>
<br />
<br />