<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Designnbuy\OrderTicket\Block\Returns\View */
?>

<?php
    $_orderticket = $block->getOrderTicket();
    $_order = $block->getOrder();
    $additionalData = $block->getAdditionalData();
?>

<div class="block block-return-details">
    <div class="block-content">
        <div class="box box-returns-requested">
            <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Request Information') ?></span></strong>
            <div class="box-content">
                <?php /* @escapeNotVerified */ echo __('ID') ?>: <?php echo $block->escapeHtml($_orderticket->getIncrementId()) ?><br>
                <?php /* @escapeNotVerified */ echo __('Order ID') ?>: <a href="<?php /* @escapeNotVerified */ echo $block->getOrderUrl($_orderticket) ?>"><?php echo $block->escapeHtml($_orderticket->getOrderIncrementId()) ?></a><br>
                <?php /* @escapeNotVerified */ echo __('Date Requested') ?>: <?php /* @escapeNotVerified */ echo $this->helper('Designnbuy\OrderTicket\Helper\Data')->getFormatedDate($_orderticket->getDateRequested()) ?><br>
                <?php /* @escapeNotVerified */ echo __('Email') ?>: <?php echo $block->escapeHtml($_order->getCustomerEmail()) ?>
                <?php if ($_orderticket->getCustomerCustomEmail()): ?>
                    <br>
                    <?php /* @escapeNotVerified */ echo __('Contact Email Address') ?>: <?php echo $block->escapeHtml($_orderticket->getCustomerCustomEmail()) ?>
                <?php endif ?>
            </div>
        </div>
        <div class="box box-treturns-shipping">
            <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Shipping Address') ?></span></strong>
            <div class="box-content">
                <address>
                    <?php /* @escapeNotVerified */ echo $block->getAddress() ?>
                </address>
            </div>
        </div>
    </div>
</div>

<div class="returns-details-items">




    <div class="block block-returns-comments">
        <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Comments') ?></strong></div>
        <div class="block-content">
            <dl class="returns-comments">
                <?php $_comments = $block->getComments(); ?>
                <?php if (!empty($_comments)): ?>
                    <?php foreach ($_comments as $_comment): ?>
                        <?php if ($_comment->getIsVisibleOnFront()): ?>
                            <dt class="returns-comment-date">
                                <strong class="returns-comment-autor">
                                    <?php if ($_comment->getIsAdmin()): ?>
                                        <?php /* @escapeNotVerified */ echo __('Customer Service')?>
                                    <?php else: ?>
                                        <?php echo $block->escapeHtml($block->getCustomerName())?>
                                    <?php endif; ?>
                                </strong>
                                <?php /* @escapeNotVerified */ echo $block->formatDate($_comment->getCreatedAt()) ?> <?php /* @escapeNotVerified */ echo $block->formatTime($_comment->getCreatedAt()) ?>
                            </dt>
                            <dd class="returns-comment-text">
                                <?php echo nl2br($block->escapeHtml($_comment->getComment())); ?>
                            </dd>
                            <dd class="returns-comment-text">
                                <?php if ($_comment->getFile()): ?>
                                    <div class="note-list-comment">
                                        <a target="_blank" href="<?php echo $block->getFile($_comment->getFile())?>"><?php echo $_comment->getFile() ?></a>
                                    </div>
                                <?php endif; ?>
                            </dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </dl>
            <form method="post"
                  id="orderticket_comment"
                  action="<?php /* @escapeNotVerified */ echo $block->getSubmitUrl() ?>"
                  class="form form-returns-comments"
                  data-mage-init='{"validation":{}}'>
                <fieldset class="fieldset">
                    <div class="field comment">
                        <label class="label"><span><?php /* @escapeNotVerified */ echo __('Leave Comment') ?></span></label>
                        <div class="control">
                            <textarea id="orderticket_comment_text" cols="5" rows="3" name="comment[comment]" data-validate="{required:true}"></textarea>
                        </div>
                    </div>
                    <div class="field admin__field">
                        <label class="admin__field-label"
                               for="file"><?php /* @escapeNotVerified */ echo __('File') ?></label>
                        <div class="upload-wrapper" data-bind="scope: 'uploader'" data-mage-init='{
                               "Magento_Ui/js/core/app": {
                                   "components": {
                                       "uploader": {
                                            "formElement" : "fileUploader",
                                            "componentType" : "fileUploader",
                                           "component": "Magento_Ui/js/form/element/file-uploader",
                                           "template": "Designnbuy_OrderTicket/components/file-uploader",
                                           "inputName": "ticket",
                                           "name": "ticket",
                                           "fileInputName": "ticket",
                                           "isMultipleFiles": false,
                                           "uploaderConfig": {
                                                "url": "<?php echo $block->getUrl('*/*/upload'); ?>"
                                           }
                                       }
                                   }
                                }
                            }
                        '>
                            <!-- ko template: getTemplate() --><!-- /ko -->
                        </div>
                    </div>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action submit primary" id="submit.save"><span><?php /* @escapeNotVerified */ echo __('Submit Comment')?></span></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
