<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Designidea sidebar recent designideas template
 *
 * @var $block \Designnbuy\Designidea\Block\Sidebar\Recent
 */
?>

<?php
    $_designideaCollection = $block->getDesignideaCollection();
?>
<?php if ($_designideaCollection->count()) { ?>
<div class="widget block block-recent-designideas" data-bind="scope: 'recemt-designideas'">
    <div class="block-title">
        <strong><?php echo __('Recent Designs') ?></strong>
    </div>
    <div class="block-content">
        <?php foreach ($_designideaCollection as $_designidea) { ?>
            <div class="item">
                <a class="designidea-item-link"
                   href="<?php echo $_designidea->getDesignideaUrl() ?>">
                    <?php echo $block->escapeHtml($_designidea->getTitle()) ?>
                </a>
            </div>

        <?php } ?>
    </div>
</div>
<?php } ?>