<?php
/**
 * Copyright © 2017 Ajay Makwana (ajay.makwana@rightwaysolution.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Designidea sidebar search form template
 *
 * @var $block \Designnbuy\Designidea\Block\Sidebar\Search
 */
?>

<div class="widget block designidea-search" data-bind="scope: 'designidea-search'">
	<div class="block-content">
		<form class="form" id="designidea_search_mini_form" action="<?php echo $block->getFormUrl() ?>" method="get">
            <div class="field search">
                <label class="label" for="designidea_search">
                    <span><?php echo __('Search') ?></span>
                </label>
                <div class="control">
                    <input id="designidea_search" type="text" name="q" value="<?php echo $block->escapeHtml($block->getQuery()) ?>" placeholder="<?php echo __('Search designs here...') ?>" class="input-text" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off">
                </div>
                <div class="actions">
                    <button type="submit" onclick="return goDesignideaSearch(this);" title="<?php echo __('Search') ?>" class="action search">
                        <span><?php echo __('Search') ?></span>
                    </button>
                </div>
            </div>

        </form>
	</div>
</div>
<script type="text/javascript">
	function goDesignideaSearch(e)
	{
		var value = document.getElementById('designidea_search').value;
		if (value) {
			window.location = e.form.action + value + '/';
		}
		return false;
	}
</script>