<?php
/**
 * Copyright © 2016 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php
/** @var \MageWorx\OptionBase\Block\Product\View\Options $block */
?>

<script>
    require([
        'jquery',
        'optionBase',
        'uiRegistry'
    ], function ($, optionBase, registry) {
        setTimeout(function(){
		$('#bss-fastorder-form-option').optionBase({
        	optionConfig: <?php echo $block->getJsonConfig()?>,
            productConfig: <?php echo $block->getProductJsonConfig()?>,
            localePriceFormat: <?php echo $block->getLocalePriceFormat()?>,
            productFinalPriceExclTax: <?php echo $block->getProductFinalPrice(false)?>,
            productRegularPriceExclTax: <?php echo $block->getProductRegularPrice(false)?>,
            productFinalPriceInclTax: <?php echo $block->getProductFinalPrice(true)?>,
            productRegularPriceInclTax: <?php echo $block->getProductRegularPrice(true)?>,
            priceDisplayMode: "<?php echo $block->getPriceDisplayMode()?>",
            catalogPriceContainsTax: "<?php echo $block->getCatalogPriceContainsTax()?>",
			extendedOptionsConfig: <?php echo $block->getExtendedOptionsConfig()?>
		});
        }, 1000);
    });
</script>