<div class="product-options product-options-bottom">
    <div id="quickedit-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": true, "animate":{"duration":"400"}, "collateral": { "openedState": "quickedit-filter-active", "element": "body" } }}'>
        <div data-role="title" class="quickedit-filter-options-title">
            <h4 class="prodtheading"><?php echo __('Quick Edit');?> <span class="greycolor"><?php echo __('INPUT DETAILS'); ?></span></h4>
        </div>
        <div data-role="content">
            <div id="quickPanel" style="float:left;width:500px;"></div>
        </div>
    </div>
</div>
<script>
    require([
        'jquery'
    ], function ($) {
        $('#quickedit-filter-block').addClass('filter-no-options');
    });
</script>
<script type="text/javascript">

    require(['jquery',
            'quickedit'
            ],
        function ($) {


            $(document).ready(function () {

            });
        });
</script>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$webpath = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
$outputHelper = $objectManager->get('Designnbuy\Base\Helper\Output');

$keyObject = $objectManager->get('Magento\Framework\Data\Form\FormKey');
$formKey = $keyObject->getFormKey();
$getLocale = $objectManager->get('Magento\Framework\Locale\Resolver');
$locale  = $getLocale->getLocale();
?>
<script type="text/javascript">
    var currentStore = '<?php echo $locale;?>';
    var uploadfile = '<?php echo $block->getUrl('orderattachment/index/upload/');?>';
    var uploadfolder = '';
    var fontUrl = '<?php echo $block->getUrl('font/font/fontlist');?>';
    var fontDirectory = '<?php echo $outputHelper->getMediaPath();?>'+ 'designnbuy/font/';
    var formkey = "<?php echo $formKey;?>";
    var fontData;
    var paper;
    var svgTextArea;
    
    var canvas;
    var direction="ltr";
    var currentSide = 0;
    var hexCodeList = [];
    var updateCurrentSide = false;
    var updateTextInterval;
    var content,globalScale;
    var typeMap_ = {px: 1};
    var baseUrl = '<?php echo $webpath ?>';
    var toolType = "web2print";
    var removeWhiteUrl = '<?php echo $block->getUrl('base/image/removewhite/');?>';
    var customerDetailUrl = '<?php echo $block->getUrl('customer/account/details/');?>';
    var generatePreviewPngUrl = '<?php echo $block->getUrl('base/index/generatePng');?>';
</script>